### ISSUE TITLE
Wildcard inheritance

### ISSUE THREAD

**Issue by smikhalevski** [Grabr/quantum-css#7]
Support build inherited properties as:
```css
.fz-l {
  &,* { font-size:large }
}
```

```scss
$wildcard-extend: (
    azimuth
    border-collapse
    border-spacing
    caption-side
    color
    cursor
    direction
    elevation
    empty-cells
    font-family
    font-size
    font-style
    font-variant
    font-weight
    font
    letter-spacing
    line-height
    list-style-image
    list-style-position
    list-style-type
    list-style
    orphans
    pitch-range
    pitch
    quotes
    richness
    speak-header
    speak-numeral
    speak-punctuation
    speak
    speech-rate
    stress
    text-align
    text-indent
    text-transform
    visibility
    voice-family
    volume
    white-space
    widows
    word-spacing
);

@mixin spread-properties($props, $value) {
  @each $prop in $props {
    @if (index($wildcard-extend, to_lower_case($prop))) {
      &, * {
        #{$prop}: $value;
      }
    }
    @else {
      #{$prop}: $value;
    }
  }
}
```
